name: Build and Deploy Docusaurus Site

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with: 
          fetch-depth: 0
          
    - uses: actions/setup-node@v4
      with:
          node-version: 18
           # cache: 'npm'
          
    - name: Install dependencies
      run: npm ci
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro

    - name: Build website
      run: npm run docusaurus build
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro

    - name: Show local dir
      run: ls "./website/generator/build"
      
    - name: Pubblica su 2nf.it_home
      #
      # ------------- https://github.com/marketplace/actions/ftp-mirror
      #
      uses: modern-dev/ftp-mirror@v2
      with:
        server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./website/generator/build"
        remote_dir: "./"
        delete: "true"
        exclude: ".ftpquota"

    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: e9e5b3f2-d32b-4a92-99c5-e3e04be60ae2
        MESSAGE: "E' stato pubblicato il sito!"

   #   You may pin to the exact commit or the version.
   #   uses: airvzxf/ftp-deployment-action@5483542d9d0055601ff0bf09c1e552f3a95c9ff8
   #   uses: airvzxf/ftp-deployment-action@latest
   #   with:
   #     # FTP Server.
   #     server: ${{ secrets.FTP_SERVER }}
   #     # FTP User.
   #     user: ${{ secrets.FTP_USERNAME }}
   #     # FTP Password.
   #     password: ${{ secrets.FTP_PASSWORD }}
   #     # Local directory.
   #     local_dir: "./website/generator/build"
   #     remote_dir: "./"
   #     max_retries: "5"

