name: Build and Deploy Docusaurus Site

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with: 
          fetch-depth: 0
          
    - uses: actions/setup-node@v4
      with:
          node-version: 18
           # cache: 'npm'
          
    - name: Install dependencies
      run: npm ci
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro

    - name: Build website
      run: npm run docusaurus build
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro
        
    - name: Pubblica su 2nf.it_home
      # You may pin to the exact commit or the version.
      # uses: airvzxf/ftp-deployment-action@5483542d9d0055601ff0bf09c1e552f3a95c9ff8
      uses: airvzxf/ftp-deployment-action@latest
      with:
        # FTP Server.
        server: ${{ secrets.FTP_SERVER }}
        # FTP User.
        user: ${{ secrets.FTP_USERNAME }}
        # FTP Password.
        password: ${{ secrets.FTP_PASSWORD }}
        # Local directory.
        local_dir: "./website/generator/build"
        remote_dir: "./"

