name: Build and Deploy Docusaurus Site

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with: 
          fetch-depth: 0
          
    - uses: actions/setup-node@v4
      with:
          node-version: 18
           # cache: 'npm'
          
    - name: Install dependencies
      run: npm ci
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro

    - name: Build website
      run: npm run docusaurus build
      working-directory: website/generator  # Aggiungi questa linea per cambiare la directory di lavoro
        
    - name: Pubblica su 2nf.it_home
      # You may pin to the exact commit or the version.
      # uses: airvzxf/ftp-deployment-action@5483542d9d0055601ff0bf09c1e552f3a95c9ff8
      uses: airvzxf/ftp-deployment-action@latest
      with:
      # FTP Server.
      server: ftp://${{ secrets.FTP_SERVER }}
      # FTP User.
      user: ${{ secrets.FTP_USERNAME }}
      # FTP Password.
      password: ${{ secrets.FTP_PASSWORD }}
      # Local directory.
      local_dir: website/generator/build
      # Remote directory.
      remote_dir: # è già fissato in 2nf.it/home
      # Delete all the files inside of the remote directory.
      delete: # optional, default is false
      # Times that the lftp will be executed if an error occurred.
      max_retries: # optional, default is 10
      # Do not create symbolic links.
      no_symlinks: # optional, default is true
      # FTP - Allow SSL encryption.
      ftp_ssl_allow: # optional, default is false
      # FTP - FEAT: Determining what extended features the FTP server supports.
      ftp_use_feat: # optional, default is false
      # FTP - Delay in seconds between NOOP commands when downloading tail of a file.
      ftp_nop_interval: # optional, default is 2
      # NET - Maximum number of operation without success. 0 unlimited. 1 no retries.
      net_max_retries: # optional, default is 1
      # NET - Ignore hard errors. When reply 5xx errors or there is too many users.
      net_persist_retries: # optional, default is 5
      # NET - Sets the network protocol timeout.
      net_timeout: # optional, default is 15s
      # DNS - 0 no limit trying to lookup an address otherwise try only this number of times.
      dns_max_retries: # optional, default is 8
      # DNS - Time for DNS queries. Set to "never" to disable.
      dns_fatal_timeout: # optional, default is 10s

