name: prova ambiente

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    name: prova ambiente
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with: 
          fetch-depth: 0
          
    - uses: actions/setup-node@v4
      with:
          node-version: 18
           # cache: 'npm'
          
    - name: Test show
      run: |
         echo "eccoci: ${{ secrets.NON }}"


